### ISSUE TITLE
depth meters aren't stackable

### ISSUE THREAD

**Issue by thelegitdolt** [LotuxPunk/depthmeter#4]
clocks and compasses are, though
since i feel like depth meters are kind of just copper variants of the clock and compass, would be cool if it was stackable too

**Comment by LotuxPunk** [comment]
Hey ! Thanks for the feedback !

I'm actually not sure on how it'd be a good feature. What's the purpose of being stackable ?

**Comment by thelegitdolt** [comment]
just for consistency lol, since clocks and compasses are
